on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Runs the action
      id: hello
      uses: ./
      with:
        my-Input: 'Shane Sully'
    # Use the output from the `hello` step
    - name: Get the output memory
      run: 
        echo "The memory was ${{ steps.hello.outputs.memory }}"
        echo "Total memory successfully outputted"
